version: "1"
services:
  client:
    container_name: jira-client
    build: ./client
    ports:
      - "3000:3000"
    depends_on:
      - server
  server:
    container_name: jira-server
    build: ./server
    environment:
      - MYSQL_PASSWORD=my-secret-pw
      - MYSQL_HOST=jira-mysql
    ports:
      - "8000:8000"
  mysql:
    image: mysql:latest
    container_name: jira-mysql
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_DATABASE: jira
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
    driver: local
    driver_opts:
      type: none
      device: C:\Users\krist\OneDrive\Работен плот\code\nodeJS\jira-clone\database_volume
      o: bind
